# Generated by Django 4.2.1 on 2023-05-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_product_actual_stock_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='dni',
            field=models.IntegerField(default=0),
        ),
    ]
